name: FTP Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # NOTE: If your project requires a build step, uncomment the 4 lines below:
      # - run: npm install -g pnpm
      # - run: pnpm install
      # - run: pnpm build

      - name: Upload to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          # local-dir: ./dist/ # Uncomment this line ONLY if you enabled the build steps above